name: Build and Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install dependencies
        run: pnpm install
          
      - name: Build Chrome Extension
        run: pnpm run build

      - name: Archive ZIP artifact
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-zip
          path: build/chrome-mv3-prod.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Determine next tag version
        id: get_tag_version
        run: |
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          major=$(echo $latest_tag | cut -d '.' -f 1 | sed 's/v//')
          minor=$(echo $latest_tag | cut -d '.' -f 2)
          next_minor=$((minor + 1))
          echo "::set-output name=tag_version::$major.$next_minor.0"
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_version.outputs.tag_version }}
          release_name: Release ${{ steps.get_tag_version.outputs.tag_version }}
          files: |
            build/chrome-mv3-prod.zip
          draft: false
          prerelease: false
